# Generated by Django 3.2 on 2021-05-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='modile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='regname',
            new_name='Registeredname',
        ),
    ]
