# Generated by Django 3.0.5 on 2021-05-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210513_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='donorregister',
            name='ill',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='Registeredname',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
