# Generated by Django 3.0.5 on 2021-05-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210521_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='donorregister',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
