# Generated by Django 3.0.5 on 2021-05-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210521_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregister',
            name='donortype',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
