# Generated by Django 3.0.5 on 2021-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_donorregister_donortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(max_length=40)),
                ('recievername', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
