# Generated by Django 3.0.5 on 2021-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_requests_requiredservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregister',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
