# Generated by Django 3.0.5 on 2021-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_requests_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodcamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campname', models.CharField(default=None, max_length=40)),
                ('address', models.CharField(default=None, max_length=40)),
                ('city', models.CharField(default=None, max_length=40)),
                ('contact', models.CharField(default=None, max_length=10)),
                ('organizername', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('startdate', models.DateField(blank=True, default=None, max_length=10, null=True)),
                ('enddate', models.DateField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
    ]
