# Generated by Django 3.0.5 on 2021-06-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_bloodcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregister',
            name='lastdonation_eligibility',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donorregister',
            name='servicetype',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
